version: '3.1'
services:
    mongo:
        build:
            context: ./mongodb
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
    mongo-seed:
        build:
            context: ./mongo-seed
        depends_on:
            - mongo
    redis:
        build:
            context: ./redis